services:
  web:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    entrypoint: /usr/src/app/entrypoint_web.sh

  db:
    image: postgres:17.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379

  celery_worker:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
    entrypoint: /usr/src/app/entrypoint_celery.sh
    command: celery -A scaw worker -l INFO

  celery_beat:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
    entrypoint: /usr/src/app/entrypoint_celery.sh
    command: celery -A scaw beat -l INFO

volumes:
  postgres_data:
